# Generated by Django 3.2.14 on 2022-07-05 14:40

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220705_1556'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='coreuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
