# Generated by Django 3.2.14 on 2022-07-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_coreuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='coreuser',
            name='acs_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
