# Generated by Django 3.2.14 on 2022-07-05 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_uuid', models.UUIDField()),
                ('meeting_id', models.CharField(max_length=10)),
                ('title', models.CharField(help_text='Name of the meeting', max_length=100)),
                ('notes', models.TextField(help_text='More info about the meeting')),
                ('start_time', models.DateTimeField(help_text='Time and date the meeting starts')),
                ('duration', models.IntegerField(help_text='duration of the meeting in seconds')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
