# Generated by Django 3.2.14 on 2022-07-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(help_text='Time and date the meeting ends', null=True),
        ),
    ]
