# Generated by Django 3.2.14 on 2022-07-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20220705_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
