# Generated by Django 3.2.14 on 2022-07-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20220705_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
