# Generated by Django 3.2.14 on 2022-07-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Help',
            new_name='HelpArticle',
        ),
    ]
